name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python build_readme.py
        cat README.md
    - name: Send email
      uses: dawidd6/action-send-mail@v2.2.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        # body: file://README.md
        to: vpved93@gmail.com
        from: Luke Skywalker # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional attachments:
        # attachments: attachments.zip,git.diff,./dist/static/main.js
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "vpved93@gmail.com"
        git config --global user.name "ved93"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
